// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAZbeOD5fGSwf3OrkW3W9o0UriUloT7UI',
    appId: '1:28626289761:web:d7482357489f28acde9620',
    messagingSenderId: '28626289761',
    projectId: 'proodonto-10de2',
    authDomain: 'proodonto-10de2.firebaseapp.com',
    storageBucket: 'proodonto-10de2.appspot.com',
    measurementId: 'G-CZZWDN90NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd0oQZa0UDVtPA4BMzOzb8oY3Y9zjs4Yo',
    appId: '1:28626289761:android:e9e9fc6f9ac64988de9620',
    messagingSenderId: '28626289761',
    projectId: 'proodonto-10de2',
    storageBucket: 'proodonto-10de2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdFky5MWefw8WLGjR5djcg7FkTa5eMsJs',
    appId: '1:28626289761:ios:c80ea70b7d461f88de9620',
    messagingSenderId: '28626289761',
    projectId: 'proodonto-10de2',
    storageBucket: 'proodonto-10de2.appspot.com',
    iosBundleId: 'com.example.proodonto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdFky5MWefw8WLGjR5djcg7FkTa5eMsJs',
    appId: '1:28626289761:ios:c80ea70b7d461f88de9620',
    messagingSenderId: '28626289761',
    projectId: 'proodonto-10de2',
    storageBucket: 'proodonto-10de2.appspot.com',
    iosBundleId: 'com.example.proodonto',
  );
}
